-- ============================================================
-- Migration 035: ドキュメント × グループ 権限マッピング — 統合済み no-op
-- ============================================================
--
-- 【2026-07 アーキテクチャ整理 Tier 3-14】document_group_permissions は
-- migration 044 で course_group_permissions（010）と統合され、object_type
-- ポリモーフィックな object_group_permissions（object_type='document'）に
-- 置き換えられた。
--
-- 本ファイルで CREATE TABLE document_group_permissions を行うと、044 が毎起動
-- 「旧テーブルを INSERT ... SELECT で移行 → DROP TABLE」するため、035 で作って
-- 044 で即座に壊すだけの往復が発生してしまう。そのため本ファイルは意図的に
-- no-op とする（002_a1_a2_a3.sql の cloned_from カラムと同じ「最終状態への
-- 巻き戻し」パターン。過去に適用済みの意味を書き換えるのではなく、現在の
-- 正本状態に file の内容を追従させる）。
--
-- 正本は backend/db/044_object_group_permissions.sql を参照。
-- ============================================================
